Marina
lucastonussi/site pull request #15
Opened 2022-09-19 21:38 UTC by marinamq

Abrindo PR, pois inseri o slider.

2022-09-19 22:44 UTC, lucastonussi requested changes
formatar o código

2022-09-19 22:44 UTC, lucastonussi commented on pages/marina.vue
> +
tem espaço em branco aqui que não precisa vir

2022-09-19 22:57 UTC, marinamq reviewed
corrigido

2022-09-19 22:57 UTC, marinamq commented on pages/marina.vue
> +
corrigi

2022-09-19 23:09 UTC, lucastonussi commented on pages/marina.vue
> +
empurra a correção para cá

2022-09-19 23:10 UTC, lucastonussi commented on pages/marina.vue
> +  .slider{
1 espaço entre o slider e o abre chaves

2022-09-19 23:10 UTC, lucastonussi commented on pages/marina.vue
> +    outline: none;
legal o style

2022-09-19 23:11 UTC, lucastonussi commented on pages/marina.vue
>          <p>{{tango.name}}</p>
espaço entre as chaves

`{{ tango.name }}`

2022-09-19 23:11 UTC, lucastonussi commented on pages/marina.vue
>          <p>{{tango.name}}</p>
espaço entre as chaves

{{ tango.name }}

2022-09-19 23:12 UTC, lucastonussi commented on pages/marina.vue
> +      <input type="range" min="1" max="500" value="100" class="slider" id="myRange">
`id='myRange'`não está sendo usado, portanto pode retirar

2022-09-19 23:13 UTC, lucastonussi commented on pages/marina.vue
> +    <div>
nesta div aqui vocẽ poderia fazer assim

```html
<div style='margin-bottom: 30px;'>
   ...seu está input aqui dentro no caso...
</div>
```

2022-09-19 23:14 UTC, lucastonussi commented on pages/marina.vue
> +    <div>
todas as tags html aceita style embutido dentro da tag

por exemplo <div style='background-color: #badbad;'> .... </div>

2022-09-19 23:23 UTC, marinamq commented on pages/marina.vue
> +
confere se foi a correção por favor.

2022-09-20 00:38 UTC, lucastonussi approved these changes

2022-09-20 00:59 UTC, merged